#! /bin/zsh

# Simple shell benchmark
shellbench() {
  for i in $(seq 1 5)
    do time $SHELL -i -c exit 
  done
}

# Get escaped unicode sequence for an emoji and copy to clipboard
emocode() {
  local output=$(python -X utf8 -c 'import json, sys; s = json.dumps(sys.argv[1]); print(s[1:-1])' "$1")
  case "$(uname)" in
    Darwin)
      printf "%s" $output | pbcopy
      ;;
    Linux)
      printf "%s" $output | xclip -sel clipboard
      ;;
  esac
}

# Export all vars in a .env file to the current shell
exportenv() {
  if [ -f .env ]; then
    export $(cat .env | xargs)
  fi
}