#!/bin/bash

echo "Initializing fresh system install..."

# Get distro for certain dependencies
detect_distro() {
  if [ -f /etc/os-release ]; then
    . /etc/os-release
    distro=$ID
  elif type lsb_release >/dev/null 2>&1; then
    distro=$(lsb_release -si | tr '[:upper:]' '[:lower:]')
  elif [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    distro=$DISTRIB_ID
  elif [ -f /etc/debian_version ]; then
    distro="debian"
  else
    distro=$(uname -s)
  fi
  echo $distro
}

# Source and export dependency vars and funcs for future subshells
DISTRO=$(detect_distro) && export DISTRO
SETUP_DIR=$HOME/.dotfiles/_setup && export SETUP_DIR
mkdir -p $HOME/.dotfiles/_setup/logs
SETUP_LOG=$HOME/.dotfiles/_setup/logs/setup.log && export SETUP_LOG
MARKER_DIR=$HOME/.dotfiles/_setup/markers && export MARKER_DIR
mkdir -p $MARKER_DIR

# Install zsh first
echo "----- Installing zsh..."
case $DISTRO in
  ubuntu|debian|pop|mint|elementary)
    sudo apt update > $SETUP_LOG 2>&1 && apt install -y zsh curl wget unzip > $SETUP_LOG 2>&1
    ;;
  arch|manjaro)
    sudo pacman -Syu --noconfirm zsh > $SETUP_LOG 2>&1
    ;;
  darwin)
    brew update > $SETUP_LOG 2>&1 && brew install zsh > $SETUP_LOG 2>&1
    ;;
  *)
    echo "Bruh why are you using this distro - install zsh manually"
    return 1
    ;;
esac

PATH=/usr/bin:$PATH && export PATH
echo $(which zsh)
chsh -s $(which zsh)

# Install everything else within zsh for installer shell configs
sudo -E zsh << EOF
  for file in $SETUP_DIR/_dependencies/*; do
    if [ -r "\$file" ]; then
      . "\$file" $DISTRO
    fi
  done
EOF

# Bars
zsh $SETUP_DIR/_kek/butHesNotaRapper

# Remove default zshrc, stow shell configs and run first time init
[ -f "$HOME/.zshrc" ] && sudo rm $HOME/.zshrc
cd $HOME/.dotfiles && stow . && exec zsh