# MaterialMonokai color theme for kitty + Sweet-KDE background

foreground #F8F8F2
background #161925

cursor #FFFFFF
selection_foreground none
selection_background #5f7a87

# normal colors
color0 #5F7A87
color1 #FF2C96
color2 #9DFF00
color3 #E6DB74
color4 #2EDCFF
color5 #B78AFF
color6 #2EDCFF
color7 #F8F8F2

# bright colors
color8  #8ca0ad
color9  #ff6b9f
color10 #b5ff4d
color11 #f0e68c
color12 #82aaff
color13 #c9a8ff
color14 #6ee7ff
color15 #ffffff
