# Theme
include themes/SweetMaterialMonokai.conf

background_opacity    0.82
background_blur 50
dynamic_background_opacity yes


# Font
font_family      MesloLGS Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.0

# Cursor
cursor_shape beam
cursor_blink_interval 0

# Scrollback
scrollback_lines 10000

# Shell
shell /usr/bin/zsh
shell_integration enabled

# Working directory
startup_session none
cwd ~

# Window
window_padding_width 4
confirm_os_window_close 0
# hide_window_decorations yes
# window_border_width 0