#!/bin/bash

echo "----- Installing git..."
case $1 in
  ubuntu|debian|pop|mint|elementary)
    apt install -y git >> $SETUP_LOG 2>&1
    ;;
  arch|manjaro)
    pacman -Syu --noconfirm git >> $SETUP_LOG 2>&1
    ;;
  darwin)
    brew install git >> $SETUP_LOG 2>&1
    ;;
  *)
    echo "Bruh why are you using this distro - install git manually"
    return 1
    ;;
esac
