#!/bin/bash

echo "----- Installing go..."
latest=$(wget -qO- "https://go.dev/VERSION?m=text" | head -n 1)
kernel=${$(uname):l}
arch=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')
go_archive="$latest.$kernel-$arch.tar.gz"
wget -q "https://go.dev/dl/$go_archive" >> /var/log/setup.log 2>&1
rm -rf /usr/local/go
tar -C /usr/local -xzf $go_archive >> /var/log/setup.log 2>&1
rm $go_archive

