#!/bin/bash

msg="\n\n----- Installing go..."
echo $msg | tee -a $SETUP_LOG 2>&1

if command -v go &> /dev/null; then
  echo "go is already installed" | tee -a $SETUP_LOG 2>&1
  return 0
fi


latest=$(wget -qO- "https://go.dev/VERSION?m=text" | head -n 1)
kernel=${$(uname):l}
arch=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')
go_archive="$latest.$kernel-$arch.tar.gz"
wget -q "https://go.dev/dl/$go_archive" >> $SETUP_LOG 2>&1
rm -rf /usr/local/go
tar -C /usr/local -xzf $go_archive >> $SETUP_LOG 2>&1
rm $go_archive

msg="----- go installation complete"
echo $msg | tee -a $SETUP_LOG 2>&1
touch $MARKER_DIR/go

