#!/bin/bash

set -e

echo "\n----- Installing nvm..."

if command -v nvm &> /dev/null; then
  echo "----- nvm is already installed"
  touch $MARKER_DIR/nvm
  return 0
fi

sudo -u $SUDO_USER bash -c "export NVM_DIR=\"$USER_HOME/.nvm\" && \
  wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash"

echo "----- nvm installation complete"
touch $MARKER_DIR/nvm