#!/usr/bin/env bash

set -e

echo "\n----- Installing ohmyposh..."

if command -v oh-my-posh &> /dev/null; then
  echo "----- ohmyposh is already installed" | tee -a $SETUP_LOG 2>&1
  touch $MARKER_DIR/ohmyposh
  return 0
fi

sudo -u $SUDO_USER bash -c "mkdir -p $USER_HOME/.local/bin && \
  wget -qO- https://ohmyposh.dev/install.sh | bash -s -- -d $USER_HOME/.local/bin"

echo "----- ohmyposh installation complete"
touch $MARKER_DIR/ohmyposh