#!/bin/bash

set -e

echo "\n----- Installing zoxide..."

if command -v zoxide &> /dev/null; then
  echo "----- zoxide is already installed"
  touch $MARKER_DIR/zoxide
  return 0
fi

sudo -u $SUDO_USER bash -c "mkdir -p $USER_HOME/.local/bin && \
  curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash"

echo "----- zoxide installation complete"

touch $MARKER_DIR/zoxide