#!/bin/bash

## For reference only (copied into installer script)
# echo "Installing zsh..."
# case $1 in
#   ubuntu|debian|pop|mint|elementary)
#     apt update && apt install -y zsh
#     ;;
#   arch|manjaro)
#     pacman -Syu --noconfirm zsh
#     ;;
#   darwin)
#     brew update && brew install zsh
#     ;;
#   *)
#     echo "Bruh why are you using this distro - install zsh manually"
#     return 1
#     ;;
# esac
# chsh -s $(which zsh)