#!/bin/zsh

set -e

echo "\n----- Installing go..."

if [ -x /usr/local/go/bin/go ]; then
  echo "----- go is already installed"
  touch $MARKER_DIR/go
  exit 0
fi

latest=$(wget -qO- "https://go.dev/VERSION?m=text" | head -n 1)
kernel=${$(uname):l}
arch=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')
go_archive="$latest.$kernel-$arch.tar.gz"
wget -q "https://go.dev/dl/$go_archive" -O /tmp/$go_archive
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf /tmp/$go_archive
rm /tmp/$go_archive

export PATH=$PATH:/usr/local/go/bin

echo "----- go installation complete"

touch $MARKER_DIR/go
