#!/bin/bash

set -e

echo "\n----- Installing go..."

if command -v /usr/local/go &> /dev/null; then
  echo "----- go is already installed"
  touch $MARKER_DIR/go
  return 0
fi

latest=$(wget -qO- "https://go.dev/VERSION?m=text" | head -n 1)
kernel=${$(uname):l}
arch=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')
go_archive="$latest.$kernel-$arch.tar.gz"
wget -q "https://go.dev/dl/$go_archive"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf $go_archive
rm $go_archive

export PATH=$PATH:/usr/local/go/bin

echo "----- go installation complete"

touch $MARKER_DIR/go
