#!/bin/bash

set -e

echo "\n----- Installing miniforge..."

if command -v conda &> /dev/null; then
  echo "----- miniforge is already installed"
  touch $MARKER_DIR/miniforge
  return 0
fi

sudo rm -rf /opt/miniforge3
install_location=/opt/miniforge3
mkdir -p $install_location
wget -q "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" -O $install_location/miniforge_install.sh
sudo sh $install_location/miniforge_install.sh -b -u -p $install_location
sudo rm $install_location/miniforge_install.sh

echo "----- miniforge installation complete"
touch $MARKER_DIR/miniforge