#!/bin/zsh

set -e

echo "\n----- Installing nvm..."

if [ -d "$USER_HOME/.nvm" ]; then
  echo "----- nvm is already installed"
  touch $MARKER_DIR/nvm
  exit 0
fi

sudo -u $SUDO_USER bash -c "export NVM_DIR=\"$USER_HOME/.nvm\" && \
  wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash"

echo "----- nvm installation complete"
touch $MARKER_DIR/nvm