#!/bin/bash

set -e

echo "\n----- Installing uv..."

if command -v uv &> /dev/null; then
  echo "----- uv is already installed"
  touch $MARKER_DIR/uv
  return 0
fi

curl -LsSf https://astral.sh/uv/install.sh | sh

echo "----- uv installation complete"
touch $MARKER_DIR/uv
