#!/bin/bash

echo -e "\nSupaHot boutta bless this setup with some bars...\n"
sleep 1
echo -e "boom.."
sleep 1
echo -e "\tbam.."
sleep 1
echo -e "\t\tbop.."
sleep 2
echo -e "\t\t\tbada-bap.."
sleep 0.6
echo -e "\t\t\t\t    boop.."
sleep 0.9
echo -e "\n"
echo -e "\t\t\t\t ██████   ██████   ██     ██" 
echo -e "\t\t\t\t ██  ██  ██    ██  ██     ██"
echo -e "\t\t\t\t ██████  ██    ██  ██  █  ██"
echo -e "\t\t\t\t ██      ██    ██  ██ ███ ██"
echo -e "\t\t\t\t ██       ██████    ███ ███ " 
echo -e "\n"
sleep 0.5
while IFS= read -r line; do
  printf "%s\n" "$line"
  sleep 0.005
done < "$SETUP_DIR/_kek/supaHotFire"
echo -e "\n"
message="\tThis system has been blessed by SupaHotFire. Restarting shell in: "
echo -ne "$message"
for i in {10..1}; do
  echo -n "$i"
  for j in {1..5}; do
    sleep 0.2
    echo -n "."
  done
  if [ $i -gt 1 ]; then
    echo -ne "\r$message            "
    echo -ne "\r$message"
  fi
done
echo -e "\n\n"