-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.95,
        inactive_opacity = 0.95,
    },
    general = {
        gaps_in = 2,
        gaps_out = 2,
        layout = "dwindle",
        snap = {
            enabled = false,
        },
    },
})

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 4.0,
    bezier = "default",
})

