#!/bin/zsh

###### Docker Utilities ######

# Formatted docker stats sorted by container name
function dockstats() {
    watch -n 1 'STATS=$(docker stats --no-stream --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.MemPerc}}\t{{.NetIO}}\t{{.BlockIO}}\t{{.PIDs}}") && 
    HEADER=$(echo "$STATS" | head -n 1) && 
    DATA=$(echo "$STATS" | tail -n +2 | sort) && 
    (echo "$HEADER" && echo "$DATA")'
}

# Color-coded docker logs for all containers, with a custom prefix to share colors between similarly named containers
# Usage: alllogs [prefix]
function docklogs() {
  local pids=()
  local colors=("31" "32" "33" "34" "35" "36" "37" "91" "92" "93" "94" "95" "96")
  local color_map=()
  local color_index=0
  local pattern="${1:-default}"
  
  for container in $(docker ps --format "{{.Names}}"); do
    local prefix
    if [[ "$pattern" == "default" ]]; then
      prefix=$(echo $container | sed -E 's/^([^-]+(-[^-]+)*).*/\1/')
    else
      prefix=$(echo $container | grep -o -E "^$pattern[^$pattern]*" || echo $container)
    fi
    
    local color=""
    for i in "${!color_map[@]}"; do
      if [[ "${color_map[$i]}" == "$prefix" ]]; then
        color="${colors[$i]}"
        break
      fi
    done
    
    if [[ -z "$color" ]]; then
      color="${colors[$color_index]}"
      color_map[$color_index]="$prefix"
      ((color_index = (color_index + 1) % ${#colors[@]}))
    fi
    
    docker logs -f $container | 
      sed -e "s/^/\x1b[${color}m${container}\x1b[0m --- /" &
    
    pids+=($!)
    echo ""
  done
  
  trap "kill ${pids[*]} 2>/dev/null" SIGINT SIGTERM
  wait
}