# shellcheck shell=bash
# Material Monokai Theme for tmux-powerline
# Colors from ~/.dotfiles/.config/nvim/lua/themes/material_monokai.lua

# Material Monokai color definitions
MM_BG="#263238"
MM_DARKER_BG="#192227"
MM_ONE_BG="#2c3940"
MM_ONE_BG2="#323f47"
MM_WHITE="#F8F8F2"
MM_GREY="#5F7A87"
MM_LIGHT_GREY="#8ca0ad"
MM_MAGENTA="#FF2C96"
MM_LIME="#9DFF00"
MM_CYAN="#2EDCFF"
MM_YELLOW="#E6DB74"
MM_PURPLE="#B78AFF"
MM_ORANGE="#FD971F"
MM_VIOLET="#B267E6"

# Default theme colors
TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-$MM_DARKER_BG}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-$MM_WHITE}

if tp_patched_font_in_use; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}

# Window status (current window)
# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_CURRENT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_CURRENT=(
		"#[$(tp_format inverse)]"
		"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
		" #I#F "
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		" #W "
		"#[$(tp_format regular)]"
		"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
	)
fi

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_STYLE" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_STYLE=(
		"$(tp_format regular)"
	)
fi

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_FORMAT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_FORMAT=(
		"#[$(tp_format regular)]"
		"  #I#{?window_flags,#F, } "
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		" #W "
	)
fi

# Left status segments
# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_LEFT_STATUS_SEGMENTS" ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"tmux_session_info $MM_LIME $MM_DARKER_BG"
		"hostname $MM_CYAN $MM_DARKER_BG"
		"lan_ip $MM_ONE_BG2 $MM_WHITE"
		"wan_ip $MM_ONE_BG2 $MM_WHITE"
		"vcs_branch $MM_PURPLE $MM_DARKER_BG"
	)
fi

# Right status segments
# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS" ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		"pwd $MM_ONE_BG2 $MM_YELLOW"
		"load $MM_ONE_BG $MM_ORANGE"
		"battery $MM_ONE_BG $MM_LIME"
		"weather $MM_CYAN $MM_DARKER_BG"
		"date_day $MM_DARKER_BG $MM_GREY"
		"date $MM_DARKER_BG $MM_WHITE"
		"time $MM_DARKER_BG $MM_WHITE"
	)
fi
