#!/usr/bin/env bash
 
if ! minikube status &>/dev/null
then
    echo "minikube isn't running" >&2
    exit 1
fi
  
kube_ip=$(minikube ip)
kube_hosts="$kube_ip phantom.kubernetes phantom.next.kubernetes dashboard.kubernetes dashboard.next.kubernetes konga.kubernetes kong-admin.kubernetes kong-proxy.kubernetes pgadmin.kubernetes kafka.kubernetes metabase.kubernetes dice.kubernetes loa.kubernetes"
  
if ! grep phantom.kubernetes /etc/hosts >/dev/null
then
    echo "Adding kubernetes entries to your hosts file"
    echo "$kube_hosts" | sudo tee -a /etc/hosts
else
    echo "Replacing minikube ip in your hosts file"
    # Fix for difference in BSD/macOS sed command
    if [[ "$OSTYPE" == "darwin"* ]]
    then
        sudo sed -E -i '' '/phantom.kubernetes/s/^[0-9]{1,3}([.][0-9]{1,3}){3}/'$kube_ip'/' /etc/hosts
    else
        sudo sed -E -i '/phantom.kubernetes/s/^[0-9]{1,3}([.][0-9]{1,3}){3}/'$kube_ip'/' /etc/hosts
    fi
fi
