#!/bin/zsh

set -e

echo "\n----- Installing argocd CLI..."

if command -v argocd &> /dev/null; then
  echo "----- argocd is already installed"
  touch $MARKER_DIR/argocd
  exit 0
fi

case $1 in
  ubuntu | debian | pop | mint | elementary)
    curl -sSL -o /tmp/argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    sudo install -m 555 /tmp/argocd-linux-amd64 /usr/local/bin/argocd
    rm /tmp/argocd-linux-amd64
    ;;
  arch | manjaro | endeavouros)
    sudo pacman -S --noconfirm argocd
    ;;
  darwin)
    brew install argocd
    ;;
  *)
    echo "bruh why are you using this distro - install argocd manually"
    exit 1
    ;;
esac

echo "----- argocd installation complete"
touch $MARKER_DIR/argocd
