#!/usr/bin/env bash

echo "Installing zsh, Oh My Posh, fzf, and zoxide..."

# Function to detect the distribution
detect_distro() {
  if [ -f /etc/os-release ]; then
    . /etc/os-release
    DISTRO=$ID
  elif type lsb_release >/dev/null 2>&1; then
    DISTRO=$(lsb_release -si | tr '[:upper:]' '[:lower:]')
  elif [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    DISTRO=$DISTRIB_ID
  elif [ -f /etc/debian_version ]; then
    DISTRO="debian"
  else
    DISTRO=$(uname -s)
  fi
  echo $DISTRO
}

DISTRO=$(detect_distro)
echo "Detected distribution: $DISTRO"

# Install zsh
install_zsh() {
  echo "Installing zsh..."
  case $DISTRO in
    ubuntu|debian|pop|mint|elementary)
      sudo apt update && sudo apt install -y zsh
      ;;
    fedora|centos|rhel)
      sudo dnf install -y zsh
      ;;
    arch|manjaro)
      sudo pacman -Syu --noconfirm zsh
      ;;
    *)
      echo "Unsupported distribution for automatic zsh installation. Please install manually."
      return 1
      ;;
  esac
  
  # Set zsh as default shell
  echo "Setting zsh as default shell..."
  chsh -s $(which zsh)
}

# Install Oh My Posh
install_oh_my_posh() {
  echo "Installing Oh My Posh..."
  curl -s https://ohmyposh.dev/install.sh | bash -s
}

# Install fzf
install_fzf() {
  echo "Installing fzf..."
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install --all
}

# Install zoxide
install_zoxide() {
  echo "Installing zoxide..."
  which curl || sudo apt install -y curl
  curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash

}

# Run installations
install_zsh
install_oh_my_posh
install_fzf
install_zoxide

echo "Dependencies installed"