#!/bin/bash

set -e

echo "\n----- Installing git..."

if command -v git &> /dev/null; then
  echo "----- git is already installed"
  touch $MARKER_DIR/git
  return 0
fi

case $1 in
  ubuntu|debian|pop|mint|elementary)
    sudo apt install -y git
    ;;
  arch|manjaro)
    sudo pacman -Syu --noconfirm git
    ;;
  darwin)
    brew install git
    ;;
  *)
    echo "bruh why are you using this distro - install git manually"
    return 1
    ;;
esac

echo "----- git installation complete"
touch $MARKER_DIR/git