#!/bin/bash

set -e

echo "\n----- Installing stow..."

if command -v stow &> /dev/null; then
  echo "----- stow is already installed"
  touch $MARKER_DIR/stow
  return 0
fi

case $1 in
  ubuntu|debian|pop|mint|elementary)
    sudo apt install -y stow
    ;;
  arch|manjaro)
    sudo pacman -Syu --noconfirm stow
    ;;
  darwin)
    brew install stow
    ;; 
  *)
    echo "bruh why are you using this distro - install stow manually"
    return 1
    ;;
esac

echo "----- stow installation complete"
touch $MARKER_DIR/stow