#!/bin/zsh

set -e

echo "\n----- Installing stow..."

if command -v stow &> /dev/null; then
  echo "----- stow is already installed"
  touch $MARKER_DIR/stow
  exit 0
fi

case $1 in
  ubuntu|debian|pop|mint|elementary)
    sudo apt install -y stow
    ;;
  arch|manjaro|endeavouros)
    sudo pacman -S --noconfirm stow
    ;;
  darwin)
    brew install stow
    ;; 
  *)
    echo "bruh why are you using this distro - install stow manually"
    exit 1
    ;;
esac

echo "----- stow installation complete"
touch $MARKER_DIR/stow